/*Datentypen.sql*/

DROP TABLE T_CHAR;
CREATE TABLE T_CHAR(
CHAR_COLUMN CHAR(20),
VARCHAR2_COLUMN VARCHAR2(20)
);

INSERT INTO T_CHAR VALUES('Hello World','Hello World' );
INSERT INTO T_CHAR VALUES('12345678901234567890','12345678901234567890' );
SELECT * FROM T_CHAR;
SELECT LENGTH(CHAR_COLUMN),LENGTH(VARCHAR2_COLUMN) FROM T_CHAR;

--inplicite Datenkonvertierung(implicit conversion)
SELECT * FROM T_CHAR WHERE CHAR_COLUMN = 'Hello World';
SELECT * FROM T_CHAR WHERE CHAR_COLUMN = 'Hello World         ';--20 
SELECT * FROM T_CHAR WHERE CHAR_COLUMN = 'Hello World                  ';
SELECT * FROM T_CHAR WHERE CHAR_COLUMN = '      Hello World          ';

SELECT * FROM T_CHAR WHERE CHAR_COLUMN =     '12345678901234567890';
SELECT * FROM T_CHAR WHERE CHAR_COLUMN =     '12345678901234567890123';
/* 01756. 00000 -  "quoted string not properly terminated */
SELECT * FROM T_CHAR WHERE CHAR_COLUMN = CAST('12345678901234567890123' AS CHAR(20));

SELECT * FROM T_CHAR WHERE VARCHAR2_COLUMN = 'Hello World';
SELECT * FROM T_CHAR WHERE VARCHAR2_COLUMN = 'Hello World  ';
SELECT * FROM T_CHAR WHERE VARCHAR2_COLUMN = '    Hello World           ';

SELECT * FROM T_CHAR WHERE CHAR_COLUMN = VARCHAR2_COLUMN;
SELECT * FROM T_CHAR WHERE CAST(CHAR_COLUMN AS VARCHAR2(20))=VARCHAR2_COLUMN;
SELECT * FROM T_CHAR WHERE CHAR_COLUMN = CAST(VARCHAR2_COLUMN AS CHAR(20));
SELECT * FROM T_CHAR WHERE VARCHAR2_COLUMN = CHAR_COLUMN;

SELECT '    Hello World       ',RTRIM('    Hello World     '),
LTRIM('   Hello World     '), TRIM('   Hello World     ') FROM DUAL;
SELECT * FROM T_CHAR WHERE TRIM(CHAR_COLUMN) = VARCHAR2_COLUMN; 

--right padding
SELECT * FROM T_CHAR WHERE CHAR_COLUMN = RPAD(VARCHAR2_COLUMN,20 );
SELECT * FROM T_CHAR WHERE CHAR_COLUMN = RPAD(VARCHAR2_COLUMN,LENGTH(CHAR_COLUMN));
--DELETE FROM T_CHAR WHERE CHAR_COLUMN='12345678901234567890';

SELECT CHAR_COLUMN, TRIM(CHAR_COLUMN), VARCHAR2_COLUMN, RPAD(VARCHAR2_COLUMN, 20 ) 
FROM T_CHAR WHERE CHAR_COLUMN = RPAD( VARCHAR2_COLUMN, 20 );

SELECT CHAR_COLUMN, TRIM(CHAR_COLUMN), VARCHAR2_COLUMN, RPAD(VARCHAR2_COLUMN, 20 ) 
FROM T_CHAR WHERE CHAR_COLUMN = RPAD( VARCHAR2_COLUMN, 20 );

SELECT LENGTH(CHAR_COLUMN),LENGTH(TRIM(CHAR_COLUMN)),LENGTH(VARCHAR2_COLUMN),
LENGTH(RPAD(VARCHAR2_COLUMN,20)) FROM T_CHAR;

--LIKE
SELECT * FROM T_CHAR WHERE CHAR_COLUMN LIKE '%rld         '; --20
SELECT * FROM T_CHAR WHERE CHAR_COLUMN LIKE 'rld';--20
SELECT * FROM T_CHAR WHERE CHAR_COLUMN LIKE '%rld%';
SELECT * FROM T_CHAR WHERE CHAR_COLUMN = 'Hello World                     ';

--Variable
VARIABLE VARCHAR2_BV VARCHAR2(20);
--exec:VARCHAR2_bv :='Hello World';








