/*TABELLEN*/

--Max. 1000 Spalten

DROP TABLE MYTABLE;
CREATE TABLE MYTABLE (
    ID INT,
    BESCHREIBUNG VARCHAR2(20)
);

INSERT INTO MYTABLE VALUES(1,'Eins');
INSERT INTO MYTABLE VALUES(2,'Zwei');

SELECT * FROM MYTABLE;

/*Primary Key column-level*/

DROP TABLE MYTABLE;
CREATE TABLE MYTABLE (
    ID INT CONSTRAINT PK_MYTABLE PRIMARY KEY,
    BESCHREIBUNG VARCHAR(20)
);
INSERT INTO MYTABLE VALUES(1,'Eins');
INSERT INTO MYTABLE VALUES(2,'Zwei');

SELECT * FROM MYTABLE;


INSERT INTO MYTABLE VALUES (2, 'Zwei');
---Error report -
ORA-00001: unique constraint (KD240283.PK_MYTABLE) violated

SELECT * FROM MYTABLE;

/*Primary Key table-level*/

DROP TABLE MYTABLE;
CREATE TABLE MYTABLE (
    ID INT,
    BESCHREIBUNG VARCHAR2(20),
    CONSTRAINT PK_MYTABLE PRIMARY KEY (ID)
)

INSERT INTO MYTABLE VALUES (1, 'Eins');
INSERT INTO MYTABLEVALUES (2, 'Zwei');

SELECT * FROM MYTABLE;

/*Primary Key per ALTER*/

DROP TABELE MYTABLE;
CREATE TABLE MYTABLE (
    ID INT,
    BESCHREIBUNG VARCHAR2(20)
);
ALTER TABLE MYTABLE
ADD CONSTRAINT PK_MYTABLE PRIMARY KEY(ID);

INSERT INTO MYTABLE VALUES (1, 'Eins');
INSERT INTO MYTABLE VALUES (2, 'Zwei');

SELECT * FROM MYTABLE;

/*DEFAULT*/

DROP TABLE MYTABLE;
CREATE TABLE MYTABLE (
    ID int,
    BESCHREIBUNG VARCHAR2(20) DEFAULT 'nix'
);
INSERT INTO MYTABLE VALUES (1, 'Eins');
INSERT INTO MYTABLE VALUES (2, 'Zwei');
INSERT INTO MYTABLE (ID) VALUES (3);

SELECT * FROM MYTABLE;

/*CREATE TABLE AS SELECT*/

DROP TABLE EMPDEPT;
CREATE TABLE EMPDEPT AS
SELECT EMP.EMPNO,EMP.ENAME,DEPT.DNAME
FROM EMP
JOIN DEPT 
ON DEPT.DEPTNO = EMP.DEPTNO;

SELECT * FROM EMPDEPT;

/*UNIQUE CONSTRAINT*/

DROP TABLE MYTABLE;
CREATE TABLE MYTABLE(
 ID INT CONSTRAINT PK_MYTABLE UNIQUE,
 BESCHREIBUNG VARCHAR2(20)
);
INSERT INTO MYTABLE VALUES (1, 'Eins');
INSERT INTO MYTABLE VALUES (2, 'Zwei');

SELECT * FROM MYTABLE;

INSERT INTO MYTABLE VALUES (2, 'Zwei'); -- ORA-00001: unique constraint (KD240279.PK_MYTABLE) violated
INSERT INTO MYTABLE VALUES (null, 'gar nix');
INSERT INTO MYTABLE VALUES (null, 'wieder nix'); -- klappt fehlerfrei!

SELECT * FROM MYTABLE;

/*CHECK*/

-- Tabelle löschen, falls sie existiert
DROP TABLE MYTABLE;

-- Tabelle neu erstellen
CREATE TABLE MYTABLE (
    ID INT NOT NULL,
    BESCHREIBUNG VARCHAR2(20),
    CONSTRAINT CK_BESCHREIBUNG CHECK (LENGTH(BESCHREIBUNG) > 3)  
);

-- Werte einfügen
INSERT INTO MYTABLE VALUES (1, 'Eins');
INSERT INTO MYTABLE VALUES (2, 'Zwei');

-- Daten abfragen
SELECT * FROM MYTABLE;

INSERT INTO MyTable VALUES (null, 'gar nix'); -- cannot insert NULL into ("KD240279"."MYTABLE"."ID") 01400. 00000 -  "cannot insert NULL into (%s)"
INSERT INTO MyTable VALUES (2, 'nix'); -- ORA-02290: check constraint (KD240279.CK_BESCHREIBUNG) violated


/*FOREIGN*/

DROP TABLE MYTABLE;
CREATE TABLE MYTABLE (
    ID INT CONSTRAINT FK_MYTABLE_ID REFERENCES DEPT(DEPTNO),
    BESCHREIBUNG VARCHAR2(20) CONSTRAINT CK_BESCHREIBUNG (LENGTH(BESCHREIBUNG) > 3
);

INSERT INTO MYTABLE VALUES (10, 'Eins');
INSERT INTO MYTABLE VALUES (20, 'Zwei');

SELECT * FROM MYTABLE;

INSERT INTO MYTABLE VALUES (null, 'gar nix');
INSERT INTO MYTABLE VALUES (50, 'nix'); -- ORA-02290: check constraint (KD240279.CK_BESCHREIBUNG) violated




