 /*Data Defintion Laguage (DDL)*/
 
SELECT 1 + 2 + 3
FROM DUAL;

SELECT * FROM emp
--WHERE JOB LIKE '%MAN_';
--WHERE JOB LIKE '%MAN%';
--WHERE JOB LIKE 'MAN%';
WHERE JOB LIKE '%MAN';

SELECT * FROM PLAYERS;

SELECT 
    NAME,
    UPPER(NAME),
    LOWER(NAME)
FROM PLAYERS;

SELECT ENAME,
    INITCAP(ENAME) 
FROM EMP;

SELECT
    STREET,
    LOWER(STREET),
    INITCAP(LOWER(STREET))
FROM PLAYERS;

SELECT * FROM PLAYERS;

SELECT NAME,
        INITIALS,
        CONCAT(CONCAT(NAME,' '),INITIALS),
        NAME || ' ' || INITIALS
FROM PLAYERS;

SELECT NAME,
    SUBSTR(NAME,1,3),
    SUBSTR(NAME,4,1)
FROM PLAYERS;

SELECT NAME,
    LENGTH(NAME),
    LENGTH(NAME ||STREET)
FROM PLAYERS;

-- Benutzen von Aliase
SELECT NACHNAME,
       LENGTH(NACHNAME) LANGE
FROM (
    SELECT NAME NACHNAME
    FROM PLAYERS
)
WHERE NACHNAME LIKE '%e%';

