/*Übung 7*/
/*zu den Tennisclubtabellen */

/*1. Ausgabe der Spielernamen, die sowohl für das Team 1 als auch für das
Team 2 gespielt haben*/

SELECT * FROM PLAYERS;
SELECT * FROM MATCHES;

SELECT PLAYERNO FROM MATCHES WHERE TEAMNO = 1;
SELECT PLAYERNO FROM MATCHES WHERE TEAMNO = 2;

SELECT * 
FROM PLAYERS P
JOIN MATCHES M
ON P.PLAYERNO = M.PLAYERNO;


SELECT T1.PLAYERNO
    FROM MATCHES T1
    JOIN MATCHES T2
ON T2.PLAYERNO = T1.PLAYERNO
AND T2.TEAMNO = 2
WHERE T1.TEAMNO = 1;

SELECT 
    PL.PLAYERNO,
    PL.NAME,
    PL.INITIALS
FROM PLAYERS PL
JOIN MATCHES T1 ON T1.PLAYERNO=PL.PLAYERNO
JOIN MATCHES T2 ON T2.PLAYERNO = T1.PLAYERNO 
AND T2.TEAMNO = 2
WHERE T1.TEAMNO = 1;

SELECT
    PL.PLAYERNO,
    PL.NAME,
    PL.INITIALS
FROM PLAYERS PL
WHERE
    EXISTS (SELECT 1 FROM MATCHES T1 WHERE T1.PLAYERNO = PL.PLAYERNO AND T1.TEAMNO = 1)
    AND
    EXISTS (SELECT 1 FROM MATCHES T2 WHERE T2.PLAYERNO = PL.PLAYERNO AND T2.TEAMNO = 2);

    
SELECT PLAYERNO FROM MATCHES WHERE TEAMNO = 1
INTERSECT
SELECT PLAYERNO FROM MATCHES WHERE TEAMNO = 2;

---HERE COUD BE MORE MISTAKES  
SELECT PL.PLAYERNO, PL.NAME, PL.INITIALS 
FROM MATCHES T1 
JOIN PLAYERS PL ON PL.PLAYERNO = T1.PLAYERNO 
INTERSECT 
SELECT PL.PLAYERNO, PL.NAME, PL.INITIALS 
FROM MATCHES T2 
JOIN PLAYERS PL ON PL.PLAYERNO = T2.PLAYERNO;


--HERE IS IS OK
SELECT PL.PLAYERNO,
        PL.NAME,
        PL.INITIALS
FROM PLAYERS PL
WHERE PL.PLAYERNO IN (
SELECT PLAYERNO FROM MATCHES WHERE TEAMNO = 1
INTERSECT --SET OPERATOR
SELECT PLAYERNO FROM MATCHES WHERE TEAMNO = 2
);



---SET OPERATOREN

/*Diese Abfrage verwendet UNION statt INTERSECT und gibt Spieler zurück, die für Team 1 ODER Team 2 (oder beide) gespielt haben*/

SELECT PL.PLAYERNO,
            PL.NAME,
            PL.INITIALS
FROM PLAYERS PL
WHERE PL.PLAYERNO IN (
SELECT PLAYERNO FROM MATCHES WHERE TEAMNO = 1
UNION --SET OPERATOR
SELECT PLAYERNO FROM MATCHES WHERE TEAMNO = 2
);

/*Diese Abfrage verwendet UNION ALL, wodurch alle Zeilen aus beiden Sätzen zurückgegeben werden, 
einschließlich Duplikaten. 
Dies bedeutet, dass die Nummer eines Spielers, der für beide Teams gespielt hat, zweimal im Ergebnissatz erscheint.*/
        
SELECT PL.PLAYERNO,
        PL.NAME,
        PL.INITIALS
FROM PLAYERS PL 
WHERE PL.PLAYERNO IN (
SELECT PLAYERNO FROM MATCHES WHERE TEAMNO = 1
UNION ALL --SET OPERATOR
SELECT PLAYERNO FROM MATCHES WHERE TEAMNO = 2
);    







